### ISSUE TITLE
shell object never has a gl attribute

### ISSUE THREAD

**Issue by sebsebgo** [stackgl/gl-now#5]
in all examples requiring gl-now with some options returns a GameShell object with a gl attribute.
but it is not working for me. did i miss something?
using it as an npm package.

``` javascript
var shell = require("gl-now")({ element: container, clearColor: [0,0,0,0] });
```

**Comment by mattdesl** [comment]
What about:

``` js
shell.on('gl-init', function() {
   //now its ready:
   console.log(shell.gl)
})
```

**Comment by sebsebgo** [comment]
yeah, thanks. that was the problem. wanted to use it with react and had to come up with another solution anyway :)
